apiVersion: v1
kind: Service
metadata:
  name: {{ include "axon-server.fullname" . }}-grpc
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.grpc.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "axon-server.selectorLabels" . | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "axon-server.fullname" . }}
  labels:
    {{- include "axon-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.gui.type }}
  ports:
    - port: {{ .Values.service.gui.port }}
      targetPort: gui
      protocol: TCP
      name: gui
  selector:
    {{- include "axon-server.selectorLabels" . | nindent 4 }}
